name: Build LaTeX document

on:
  push:
    branches: [ main ]
    paths:
      - 'latex/masterthesis.tex'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: latex
    steps:
      - name: Check out latest version of main branch
        uses: actions/checkout@v3

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: masterthesis.tex
          glob_root_file: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: masterthesis.pdf 
