# This is a basic workflow to help you get started with Actions

name: Build LaTeX document

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths:
      - 'latex/masterthesis.tex'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out latest version of main branch
        uses: actions/checkout@v3

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: latex/masterthesis.tex
          glob_root_file: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: latex/masterthesis.pdf
